tap "homebrew/bundle"
tap "microsoft/git"
tap "oven-sh/bun"
tap "withgraphite/tap"
brew "git"
brew "neovim"
brew "node@18", link: true
brew "postgresql@15", link: true
brew "python@3.11"
brew "yarn"
brew "oven-sh/bun/bun"
brew "withgraphite/tap/graphite"
cask "android-studio"
cask "brave-browser"
cask "discord"
cask "docker"
cask "fig"
cask "git-credential-manager-core"
cask "google-chrome"
cask "lens"
cask "obsidian"
cask "raycast"
cask "visual-studio-code"
cask "warp"
cask "zoom"
