tap "homebrew/bundle"
tap "microsoft/git"
brew "git"
brew "krb5"
brew "node@18", link: true
brew "postgresql@15", link: true
brew "python@3.11"
brew "yarn"
cask "android-studio"
cask "brave-browser"
cask "discord"
cask "docker"
cask "fig"
cask "git-credential-manager-core"
cask "google-chrome"
cask "lens"
cask "obsidian"
cask "raycast"
cask "visual-studio-code"
cask "warp"
cask "zoom"
cask "postman"
cask "slack"
